config/routes.rb
FavoriteBeers::Application.routes.draw do
  get "/beers/about" => "beers#about"
  get "/beers" => "beers#index", as: "beers"

  get "/beers/new" => "beers#new", as: "new_beer"
  post "/beers" => "beers#create"

  get "/beers/:id" => "beers#show", as: "beer"
  delete "/beers/:id" => "beers#destroy", as: "delete"

  get "/beers/:id/edit" => "beers#edit", as: "edit_beer"
  patch "/beers/:id" => "beers#update"

end

app/models/beer.rb
class Beer < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  def index
    if params[:brewery_sort].present?
      @beers = Beer.order(:brewery)
    elsif params[:beer_sort].present?
      @beers = Beer.order(:name)
    elsif params[:abv_sort].present?
      @beers = Beer.order('abv desc')
    elsif params[:search].present?
      @beers = Beer.where("name LIKE ? OR brewery LIKE ? OR style LIKE ?",
                          "%#{params[:search]}%",
                          "%#{params[:search]}%",
                          "%#{params[:search]}%")
    else
      @beers = Beer.all
    end
  end

  def new
  end

  def create
    @beer = Beer.new
    @beer.name = params[:name]
    @beer.style = params[:style]
    @beer.abv = params[:abv]
    @beer.brewery = params[:brewery]
    @beer.nationality = params[:nationality]
    @beer.save

    redirect_to beers_url
  end

  def edit
    @beer = Beer.find(params[:id])
  end

  def update
    @beer = Beer.find(params[:id])
    @beer.name = params[:name]
    @beer.style = params[:style]
    @beer.abv = params[:abv]
    @beer.brewery = params[:brewery]
    @beer.nationality = params[:nationality]
    @beer.save

    redirect_to beers_url
  end

  def show
    @beer = Beer.find(params[:id])
    # @beer.name = params[:title]
    # @beer.style = params[:style]
    # @beer.abv = params[:abv]
    # @beer.brewery = params[:brewery]
  end

  def destroy
    @beer = Beer.find(params[:id])
    @beer.destroy

    redirect_to beers_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/about.html.erb
<div class="container">
<br>
<h1>It's what's for dinner.</h1>

</div>

app/views/beers/edit.html.erb
<div class="container">
  <h3>Edit <%= @beer.name %></h3>
  <%= form_tag beer_url(@beer.id), method: "patch" do %>

  <%= label_tag "name", "Beer Name"  %>
  <%= text_field_tag "name", value = @beer.name %>
  <br>
  <%= label_tag "brewery" %>
  <%= text_field_tag "brewery", value = @beer.brewery %>
  <br>
  <%= label_tag "style" %>
  <%= text_field_tag "style", value = @beer.style %>
  <br>
  <%= label_tag "nationality" %>
  <%= text_field_tag "nationality", value = @beer.nationality %>
  <br>
  <%= label_tag "abv", "ABV" %>
  <%= number_field_tag "abv", value = @beer.abv, step: 0.1  %>
  <br>

  <%= submit_tag "Save" %>


  <% end %>
</div>

app/views/beers/index.html.erb
<div class="container">
  Sort by:
  <%= link_to "Brewery", beers_url(brewery_sort: "brewery") %> |
  <%= link_to "Name", beers_url(beer_sort: "name") %> |
  <%= link_to "ABV", beers_url(abv_sort: "abv") %>
  <% @beers.each do |beer| %>
      <div class="listitem">
        <span class="cats"><%= link_to beer.name, beer_url(beer.id) %></span> by <%= beer.brewery %>

      </div>
    <% end %>
</div>

app/views/beers/new.html.erb
<div class="container">
<h3>Add a Beer</h3>
<%= form_tag beers_url, method: "post" do %>

<%= label_tag "name", "Beer Name" %>
<%= text_field_tag "name" %>
<br>
<%= label_tag "brewery" %>
<%= text_field_tag "brewery" %>
<br>
<%= label_tag "style" %>
<%= text_field_tag "style" %>
<br>
<%= label_tag "nationality" %>
<%= text_field_tag "nationality" %>
<br>
<%= label_tag "abv", "ABV" %>
<%= number_field_tag "abv", value=nil, step: 0.1 %>
<br>

<%= submit_tag "Add" %>


<% end %>
</div>

app/views/beers/show.html.erb
<div class="container">
  <h2><%= @beer.name %></h2>
  <h4>by <%= @beer.brewery %></h4>
  <span class="cats">Style: </span><%= @beer.style %>
  <br>
  <span class="cats">Nationality: </span><%= @beer.nationality %>
  <br>
  <span class="cats">ABV: </span><%= @beer.abv %>
  <br>
  <!-- <img src= "<%#= @beer.img %>" class="profile_img"> -->

  <br>
  <span><%= link_to "Edit", edit_beer_url(@beer.id) %></span> |
  <span><%= link_to "Delete", delete_url(@beer.id), method: "delete" %></span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FavoriteBeers</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body>
  <header>
      <div class="bs-example bs-navbar-top-example">
          <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-6">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <!-- <a class="navbar-brand" href="#">Brand</a> -->

            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-6">
              <ul class="nav navbar-nav">
                <li><a href="/beers" ><i class="fa fa-beer"></i></a></li>
                <li><a href="/beers/new" id="navh"><i class="fa fa-plus-circle"></i></a></li>
                <li><a href="/beers/about" id="navh"><i class="fa fa-info"></i></a></li>


                <li class="searchform">
                  <form action="/beers" role="search">
                    <input name="search" type="text" class="form-control" placeholder="Search">
                </li>
                <li class="searchform">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </form>
                </li>


              </ul>
            </div><!-- /.navbar-collapse -->
          </nav>
        </div><!-- /example -->

    </header>

<div class="background-img">
<%= yield %>
</div>
</body>
</html>